// Getters
export const IS_LOADING = 'IS_LOADING';
export const TOKEN = 'TOKEN';
export const IMAGES = 'IMAGES';
export const SELECTED_IMAGE = 'SELECTED_IMAGE';

// Mutations
export const MUTATE_UPDATE_TOKEN = 'MUTATE_UPDATE_TOKEN';
export const MUTATE_UPDATE_IS_LOADING = 'MUTATE_UPDATE_IS_LOADING';
export const MUTATE_FETCH_IMAGES = 'MUTATE_FETCH_IMAGES';
export const MUTATE_SET_SELECTED_IMAGE = 'MUTATE_SET_SELECTED_IMAGE';

// Actions
export const OBTAIN_TOKEN = 'OBTAIN_TOKEN';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';
export const UPDATE_IS_LOADING = 'UPDATE_IS_LOADING';
export const FETCH_IMAGES = 'FETCH_IMAGES';
export const SET_IMAGES = 'SET_IMAGES';
export const GET_IMAGE_DETAIL = 'GET_IMAGE_DETAIL';